services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: board-api-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    depends_on:
      - postgres
    build: .
    container_name: board-api-nest
    ports:
      - "3001:3001"
    env_file:
      - .env 
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: board-api-postgres