services:
  postgres:
    image: postgres:16-alpine
    container_name: board-api-postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: board-api-postgres
