export const ACCESS_TOKEN_EXPIRES_IN = 60 * 60;
export const REFRESH_TOKEN_EXPIRES_IN = 60 * 60 * 24 * 7;
export const COOKIE_ACCESS_TOKEN_EXPIRES_IN = ACCESS_TOKEN_EXPIRES_IN * 1000;
export const COOKIE_REFRESH_TOKEN_EXPIRES_IN = REFRESH_TOKEN_EXPIRES_IN * 1000;
